export const spacesConstants = {
	MANAGEMENT_SPACE_INIT: '@MANAGEMENT_SPACE_INIT',
	MANAGEMENT_SPACE_SUCCESS: '@MANAGEMENT_SPACE_SUCCESS',
	MANAGEMENT_SPACE_FAILURE: '@MANAGEMENT_SPACE_FAILURE',

	GET_ALL_SPACES_INIT: '@GET_ALL_SPACES_INIT',
	GET_ALL_SPACES_SUCCESS: '@GET_ALL_SPACES_SUCCESS',
	GET_ALL_SPACES_FAILURE: '@GET_ALL_SPACES_FAILURE',

	GET_SPACE_BY_ID_INIT: '@GET_SPACE_BY_ID_INIT',
	GET_SPACE_BY_ID_SUCCESS: '@GET_SPACE_BY_ID_SUCCESS',
	GET_SPACE_BY_ID_FAILURE: '@GET_SPACE_BY_ID_FAILURE',

	DELETE_SPACE_BY_ID_INIT: '@DELETE_SPACE_BY_ID_INIT',
	DELETE_SPACE_BY_ID_SUCCESS: '@DELETE_SPACE_BY_ID_SUCCESS',
	DELETE_SPACE_BY_ID_FAILURE: '@DELETE_SPACE_BY_ID_FAILURE',

	TOGGLE_SELECTED_SPACE: '@TOGGLE_SELECTED_SPACE',
};
